[package]
name = "sn-assets"
description = "Finds and loads Unity objects across the game's bundles (read-only)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
sn-dotnet.workspace = true
sn-install.workspace = true
sn-terrain.workspace = true
sn-unity.workspace = true
sn-world.workspace = true

[dev-dependencies]

[lints]
workspace = true
